import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// API sidebar is generated by docusaurus-plugin-openapi-docs (run gen-api-docs first).
// The generated file exports the items array directly as its default export.
// If it's missing or empty, we still want the build to surface a clear message
// rather than silently shipping a broken API reference (which causes
// "cant find current sidebar in context" SSR errors on every *.tag.mdx page).
let apiSidebarItems: any[] = [];
try {
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  const mod = require('./docs/api/sidebar');
  apiSidebarItems = mod.default ?? mod;
} catch (err) {
  console.warn(
    '[sidebars.ts] Could not load docs/api/sidebar — run `npm run gen-api-docs` first.',
    (err as Error).message,
  );
}

if (process.env.NODE_ENV === 'production' && apiSidebarItems.length === 0) {
  throw new Error(
    '[sidebars.ts] docs/api/sidebar is empty. ' +
      'Check that openapi.yaml contains `x-tagGroups` (required by ' +
      "`sidebarOptions.groupPathsBy: 'tagGroup'`) and re-run `npm run gen-api-docs`.",
  );
}

// Maps each generated domain group label to its hand-written overview doc.
// Uses folder-prefixed IDs: docs/api-reference/<file>.md → "api-reference/<file>"
const DOMAIN_DOCS: Record<string, string> = {
  'Service Management':       'api-reference/service-management',
  'Customers & Partners':     'api-reference/customers-partners',
  'Users & Access':           'api-reference/users-access',
  'Billing & Finance':        'api-reference/billing-finance',
  'Communications':           'api-reference/communications',
  'Workspace & Operations':   'api-reference/workspace-operations',
  'Integrations & Automation':'api-reference/integrations-automation',
  'Platform & Admin':         'api-reference/platform-admin',
};

// Inject domain overview pages into the generated sidebar:
// - Adds a clickable `link` to each domain category header
// - Inserts the domain overview doc as the first item inside the category
// - Removes the repeated API info stub that the plugin places in every group
function enrichDomainCategories(items: any[]): any[] {
  return items.map((item) => {
    const docId = DOMAIN_DOCS[item.label];
    if (item.type === 'category' && docId) {
      const childItems = (item.items ?? []).filter(
        (i: any) => !(i.type === 'doc' && i.id === 'api/warrantyflow-v-3-api'),
      );
      return {
        ...item,
        link: {type: 'doc', id: docId},
        items: [{type: 'doc', id: docId, label: 'Overview'}, ...childItems],
      };
    }
    return item;
  });
}

const sidebars: SidebarsConfig = {
  // Main documentation sidebar (non-API content)
  docsSidebar: [
    {type: 'autogenerated', dirName: 'getting-started'},
    {type: 'autogenerated', dirName: 'user-guides'},
    {type: 'autogenerated', dirName: 'create-service'},
    {type: 'autogenerated', dirName: 'sharing-service'},
    'faq',
    'release-notes',
    'support',
    {
      type: 'link',
      label: '⚡ API Reference',
      href: '/docs/api-reference/api-getting-started',
    },
  ],

  // API Reference sidebar — "APIs" root → domain groups → tag categories → endpoints
  apisidebar: [
    {
      type: 'category',
      label: 'APIs',
      collapsible: false,
      collapsed: false,
      items: [
        'api-reference/api-getting-started',
        ...enrichDomainCategories(apiSidebarItems),
      ],
    },
  ],
};

export default sidebars;
